### ISSUE TITLE
Create 'PeaceGeeks Board' as PeaceGeeks Team on SF

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/SalesForce#6]

**Comment by PeaceGeeksProjects** [comment]
Can you please elaborate? What is the purpose of this?

**Comment by PeaceGeeks** [comment]
The Board of Directors is not a team - I can't choose to add someone to it.
Perhaps we don't need it because we have the Board Flag? If so, why did we
choose a flag instead of a Team?




*Renee Black*,
*Executive Director*
#210 - 128 West Hastings Street
Vancouver, BC, V6B 1G8
*p.* 778-235-7458 | *e.* renee@peacegeeks.org
*skype.* reneeontheroad

**Comment by PeaceGeeksProjects** [comment]
Because they can be board members and volunteer in a team as well...  With a flag you can certainly "add someone to it".

**Comment by PeaceGeeks** [comment]
Ok




*Renee Black*,
*Executive Director*
#210 - 128 West Hastings Street
Vancouver, BC, V6B 1G8
*p.* 778-235-7458 | *e.* renee@peacegeeks.org
*skype.* reneeontheroad
